//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMag.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMag.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMag version 1.0
        ///
        ///Type &quot;help&quot; or &quot;?&quot; for help..
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a visualization of the water system in a data set..
        /// </summary>
        internal static string CreateGraph {
            get {
                return ResourceManager.GetString("CreateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeps the vertical spacing between the nodes equal when set to true..
        /// </summary>
        internal static string CreateGraph_EqualSpacing {
            get {
                return ResourceManager.GetString("CreateGraph_EqualSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal spacing between the nodes..
        /// </summary>
        internal static string CreateGraph_HorizontalSpacing {
            get {
                return ResourceManager.GetString("CreateGraph_HorizontalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path where a screenshot of the visualization must be saved..
        /// </summary>
        internal static string CreateGraph_OutputImage {
            get {
                return ResourceManager.GetString("CreateGraph_OutputImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical spacing between the nodes..
        /// </summary>
        internal static string CreateGraph_VerticalSpacing {
            get {
                return ResourceManager.GetString("CreateGraph_VerticalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting NMag as console application allows for quick operations without the GUI by using commands.
        ///
        ///&quot;commands&quot; - Show a list of available commands.
        ///&quot;&lt;command&gt; help&quot; - Get information about the command and parameters.
        ///&quot;&lt;command&gt; (&lt;Parameter&gt;=&lt;Argument&gt;)&quot; - Execute the command with the provided parameters.
        ///&quot;clear&quot; - Clear the console.
        ///
        ///The supported NMag operations can be automated by sending the commands as arguments when starting the console application..
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a data set from a file into memory..
        /// </summary>
        internal static string LoadDataSet {
            get {
                return ResourceManager.GetString("LoadDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute path of the data set..
        /// </summary>
        internal static string LoadDataSet_Path {
            get {
                return ResourceManager.GetString("LoadDataSet_Path", resourceCulture);
            }
        }
    }
}
